[project]
name = "hexlet-solutions"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "hexlet-immutable-fs-trees>=0.1.8",
]
